[package]
name = "rflv"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["example/"]

[features]
default = [ "low_level", "file" ]

low_level = []
file = []

[dependencies]
bitflags = "2.10.0"
byteorder = "1.5.0"
thiserror = "2.0.17"
